import { StyleSheet } from "react-native";
import { AppTheme } from "@/constants/theme";

export const allHabitsCompletePopupStyles = StyleSheet.create({
  popupLayer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  popupShell: {
    flex: 1,
    width: "100%",
    paddingHorizontal: AppTheme.spacing.pageHorizontal,
    justifyContent: "flex-end",
    position: "relative",
  },
  sceneCard: {
    ...StyleSheet.absoluteFillObject,
    left: -AppTheme.spacing.pageHorizontal,
    right: -AppTheme.spacing.pageHorizontal,
    top: 0,
    bottom: 0,
  },
  scene: {
    flex: 1,
    overflow: "hidden",
    alignItems: "stretch",
    justifyContent: "flex-end",
  },
  treeImage: {
    position: "absolute",
    left: "50%",
    marginLeft: -220,
    bottom: 186,
    width: 440,
    height: 380,
  },
  animatedWorm: {
    position: "absolute",
    left: 8,
    bottom: 176,
    zIndex: 3,
  },
  animatedButterfly: {
    position: "absolute",
    left: "50%",
    marginLeft: 54,
    bottom: 332,
  },
  skipButton: {
    position: "absolute",
    right: 10,
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "rgba(247, 251, 239, 0.92)",
    borderWidth: 1,
    borderColor: "#D3E2BE",
    alignItems: "center",
    justifyContent: "center",
  },
  skipButtonText: {
    fontSize: 14,
    fontFamily: AppTheme.fonts.semibold,
    color: AppTheme.colors.textSubtle,
  },
  fullWorm: {
    width: 118,
    height: 62,
    position: "relative",
  },
  wormSegment: {
    position: "absolute",
    overflow: "hidden",
    justifyContent: "flex-end",
    alignItems: "center",
    shadowColor: "#43633D",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  wormSegmentHighlight: {
    position: "absolute",
    top: 2,
    left: 3,
    borderRadius: 999,
  },
  wormSegmentBelly: {
    position: "absolute",
    bottom: 2,
    borderRadius: 999,
  },
  wormHead: {
    position: "absolute",
    right: -6,
    top: 0,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#43633D",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    zIndex: 2,
  },
  wormBridge: {
    position: "absolute",
    right: 16,
    top: 20,
    width: 18,
    height: 18,
    borderRadius: 999,
    overflow: "hidden",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  wormBridgeHighlight: {
    width: 8,
    height: 4,
  },
  wormBridgeBelly: {
    width: 10,
    height: 4,
  },
  wormHeadSvg: {
    position: "absolute",
    top: -2,
    left: 0,
    width: 40,
    height: 40,
  },
  butterfly: {
    width: 34,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  butterflyWing: {
    position: "absolute",
    top: 6,
    width: 14,
    height: 18,
    borderRadius: 12,
    borderWidth: 1,
  },
  butterflyWingLeft: {
    left: 2,
  },
  butterflyWingLeftPalette: {
    backgroundColor: "#FFD96A",
    borderColor: "#D99A2B",
  },
  butterflyWingRight: {
    right: 2,
  },
  butterflyWingRightPalette: {
    backgroundColor: "#FFD96A",
    borderColor: "#D99A2B",
  },
  butterflyBody: {
    position: "absolute",
    top: 7,
    width: 6,
    height: 16,
    borderRadius: 999,
    backgroundColor: "#5F4A33",
  },
  butterflyHead: {
    position: "absolute",
    top: 3,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#5F4A33",
  },
  butterflyAntennaLeft: {
    position: "absolute",
    top: -1,
    left: 13,
    width: 2,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#5F4A33",
    transform: [{ rotate: "-28deg" }],
  },
  butterflyAntennaRight: {
    position: "absolute",
    top: -1,
    right: 13,
    width: 2,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#5F4A33",
    transform: [{ rotate: "28deg" }],
  },
});
